FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD jenkinsTestId.jar /opt/jenkinsTestId/
EXPOSE 8080
WORKDIR /opt/jenkinsTestId/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "jenkinsTestId.jar"]
